### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by eddelbuettel** [ess-intro/presentation-ess-base-install#1]
Thanks for for staeting the repo!  

Please see what I commented https://github.com/ess-intro/presentation-ess-from-spacemacs/issues/1 and (IIRC) on the collabedit page.  Might be best to have consistent naming for the repos to keep track of things -- so could you maybe rename to 'presentation-ess-installation'?  

Also, I guess we may want to delineate between "base Emacs/ESS" and "spacemacs ESS".  Thoughts?

**Comment by eddelbuettel** [comment]
Thanks for changing this so promptly!  :heart:

**Comment by plantarum** [comment]
No problem. Thanks Dirk!
